### ISSUE TITLE
query for high confidence tfac2gene links only

### ISSUE THREAD

**Issue by makuintnu** [BioGateway/cytoscape-app#39] opened 2020-08-27 16:23 UTC
Apparently this doesn't work, the results file contains many entries with low confidence?
![image](https://user-images.githubusercontent.com/17412163/91468372-33ca8100-e892-11ea-99f8-3e7b2436b972.png)
![image](https://user-images.githubusercontent.com/17412163/91468514-65434c80-e892-11ea-924e-304bf4a26654.png)

**Comment by sholmas** [comment] 2020-09-30 09:19
It does work for me. However, there is an issue with getting query constraints to apply to a queries if the query builder was opened before the constraints was added. If the query builder is reopened after adding the constraints, it should work. 

*Note*
To keep the query you've built, use the "SPARQL Code" tab to copy the raw query, then paste and parse it into the new query builder window after closing and reopening it.

**Comment by sholmas** [comment] 2020-09-30 09:31
This seems to be caused by issue #40 .

**Closed as completed by sholmas** 2020-09-30 09:31 UTC
